### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by xenofree** [Super-Visions/icingaweb2-module-itop#1]
Hi,

I couldn't add an iTop import source on icinga2 (v2.8.0)  (icinweb2 v2.5.0, icingaweb2-module-director-1.4.1)  under freebsd 11.0.

This is the issue : 

![image](https://user-images.githubusercontent.com/35098906/34559845-ca861440-f143-11e7-8cdd-dcd7d82d851d.png)

Invalid argument supplied for foreach()

#0 /usr/local/www/icingaweb2/modules/itop/library/Itop/Util.php(36): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'Invalid argumen...', '/usr/local/www/...', 36, Array)
#1 /usr/local/www/icingaweb2/modules/itop/library/Itop/ProvidedHook/Director/ImportSource.php(71): Icinga\Module\Itop\Util::enumQueries('iTop')
#2 /usr/local/www/icingaweb2/modules/director/application/forms/ImportSourceForm.php(103): Icinga\Module\Itop\ProvidedHook\Director\ImportSource::addSettingsFormFields(Object(Icinga\Module\Director\Forms\ImportSourceForm))
#3 /usr/local/www/icingaweb2/modules/director/application/forms/ImportSourceForm.php(45): Icinga\Module\Director\Forms\ImportSourceForm->addSettings()
#4 /usr/local/www/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(356): Icinga\Module\Director\Forms\ImportSourceForm->setup()
#5 /usr/local/www/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(517): Icinga\Module\Director\Web\Form\QuickForm->prepareElements()
#6 /usr/local/www/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(530): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#7 /usr/local/www/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(367): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#8 /usr/local/www/icingaweb2/modules/director/application/controllers/ImportsourceController.php(47): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#9 /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ImportsourceController->addAction()
#10 /usr/local/www/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('addAction')
#11 /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/local/www/icingaweb2/library/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#13 /usr/local/www/icingaweb2/library/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#14 /usr/local/www/icingaweb2/public/index.php(4): require_once('/usr/local/www/...')
#15 {main}

I have provide an iTop entry in resources.ini

[iTop]
type = "iTop"
url = "*******"
username = "*******"
password = "*******"

And receive an HTTP 200 from iTop

[04/Jan/2018:11:21:53 +0100] "POST /webservices/rest.php?version=1.3 HTTP/1.1" 200 46

Is there any way to fix this ?

Regards,

**Comment by Hipska** [comment]
2 questions:

1. Which version of php are you using?
2. How many queries do you have in your iTop Query phrasebook?

**Comment by Hipska** [comment]
Hi @xenofree, I released a new version of this module with a fix for your problem.
