### ISSUE TITLE
Key column name confirmation of behavior

### ISSUE THREAD

**Issue by timeos** [Super-Visions/icingaweb2-module-itop#3]
Hello

at first thank you for this great connector, its very useful and I had chance to test it already. I have one question about behavior of this "Key column name" field in my setup:
- I am syncing multiple object types from iTop into icinga for Host objects (servers, virtual servers, network devices) so I have multiple "import source" records in icinga
- at first I have used "name" as "Key column name" in all that import sources as the equipment name of all that various kind of types are always unique. 
- but I have realized, that using "name" is not a good approach, as in case of changing device name in iTop, it will be handled as completely new device and the one with old name will be deleted during sync process. 
- thus I decided to use object "id" instead. I used it within all "import source" records.
- but now I am getting strange issues about duplicate entries thus I wanted to confirm:

the values for "Key column name" attribute must be unique across all "import source" records or must be unique only within context of used "import source" record?

the value has to be unique across all "import sources" (I guess this is the case), then could it be possible to adjust/update this module to make this value to be unique only within the scope of "import source" where object was imported?
I am thinking to include for example the name/id of "import source" record itself into this "reconciliation" in addition to selected "Key column name" so we will be sure that there will be no reconciliation collision between objects from various "import source" records?

thank you for considering this option

regards and thanks again for this great module

**Comment by timeos** [comment]
another option could be to allow providing multiple "key column name" fields to be used within "import source" for reconciliation.

**Comment by Hipska** [comment]
Hi,

The "key column name" attribute is something common for all Director import modules, so it might help if you ask your questions on the [Monitoring Portal](https://monitoring-portal.org/c/icinga/director) directly.

**Comment by timeos** [comment]
understand, thanks
